config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
	resources :posts do
	 	resources :comments
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :commenter, presence: true
  validates :body, presence: true
  belongs_to :post
  belongs_to :category
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  # GET /posts/:post_id/comments
  # GET /posts/:post_id/comments.json

  def index
    #@comments = Comment.all
    #1st you retrieve the post thanks to params[:post_id]
    #2nd you get all the comments of this post
    if params[:category].blank?
      post = Post.find(params[:post_id])
      @comments = post.comments
    else
      @category = Category.find_by_name(params[:category])
      post = Post.find(params[:post_id])
      @comments = post.comments.where(category: @category)
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  # GET /posts/:post_id/comments/:id
  # GET /posts/:post_id/comments/:id.json
  def show
    #1st you retrieve the post thanks to params[:post_id]
    #2nd you retrieve the comment thanks to params[:id]
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
  end

  # GET /comments/new
  # GET /posts/:post_id/comments/new
  def new
    #1st you retrieve the post thanks to params[:post_id]
    #2nd you build a new one
    #@comment = Comment.new
    post = Post.find(params[:post_id])
    @comment = post.comments.build
  end

  # GET /comments/1/edit
  # GET /posts/:post_id/comments/:id/edit
  def edit
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  # POST /posts/:post_id/comments
  # POST /posts/:post_id/comments.json
  def create
    #1st you retrieve the post thanks to params[:post_id]
    #2nd you create the comment with arguments in params[:comment]
    #@comment = Comment.new(comment_params)

    post = Post.find(params[:post_id])
    @comment = post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        #format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.html { redirect_to([@comment.post, @comment], notice: 'Comment was successfully created.' )}
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  # PUT /posts/:post_id/comments/:id
  # PUT /posts/:post_id/comments/:id.json
  def update
    #1st you retrieve the post thanks to params[:post_id]
    #2nd you retrieve the comment thanks to params[:id]
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to([@comment.post, @comment], notice: 'Comment was successfully updated.' )}
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  # DELETE /posts/:post_id/comments/1
  # DELETE /posts/:post_id/comments/1.json

  def destroy
    #1st you retrieve the post thanks to params[:post_id]
    #2nd you retrieve the comment thanks to params[:id]
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      #1st argument reference the path /posts/:post_id/comments/
      #format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.html { redirect_to post_comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenter, :body, :post_id, :category_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%#= form_with(model: comment, local: true) do |form| %>
<%= form_for([@comment.post, @comment]) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :commenter %>
    <%= form.text_field :commenter %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%#= link_to 'Show', @comment %> <%= link_to 'Show', [@comment.post, @comment] %>|
<%#= link_to 'Back', comments_path %>
<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenter</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <br>
    <hr>
    <br>
    <% Category.all.each do |cat| %>
      <%= link_to cat.name, post_comments_path(category: cat.name) %>
    <% end %>
    <br>
    <hr>
    <br>

    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= comment.category_id %></td>
        <!--td><%#= link_to 'Show', comment %></td-->
        <td><%= link_to 'Show', [comment.post, comment] %></td>
        <!--td><%#= link_to 'Edit', edit_comment_path(comment) %></td-->
        <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></td>
        <!--td><%#= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
        <td><%= link_to 'Destroy', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Comment', new_comment_path %>
<%= link_to 'New Comment', new_post_comment_path %>

app/views/comments/new.html.erb
<!--h1>New Comment</h1-->

<%#= render 'form', comment: @comment %>

<%#= link_to 'Back', comments_path %>

<h1>New comment</h1>

<%= render 'form', comment: @comment.post %>

<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', post_comments_path(@comment.post)%>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.category_id %>
</p>

<%#= link_to 'Edit', edit_comment_path(@comment) %> |
<%#= link_to 'Back', comments_path %>

<!-- /posts/:post_id/comments/:id/edit -->
<%= link_to 'Edit', edit_post_comment_path(@comment.post, @comment) %> |
<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', post_comments_path(@comment.post) %>